// Generated by CoffeeScript 1.9.2
var app;

app = app || {};

app.game = {
  start_random_game: function() {
    console.log("start_random_game");
    app.menu.hide();
    app.game.show();
  },
  start_private_game: function() {
    console.log("start_private_game");
  },
  exit: function() {}
};
